### PR TITLE
Incremented version to 1.3.2.

### PR DESCRIPTION
**Pull request by gaiksaya**
Signed-off-by: Sayali Rohidas Gaikawad <gaiksaya@amazon.com>

Coming from https://github.com/opensearch-project/opensearch-build/issues/1805 post release activity.

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by sruti1312** [comment]
@gaiksaya Do we still need this PR, considering we are upgrading the main to 2.0?

**Comment by gaiksaya** [comment]
> @gaiksaya Do we still need this PR, considering we are upgrading the main to 2.0?

Yes this PR is towards 1.3 branch and not main. For any future patch releases we are preparing the branch to be up-to-date and ready.
Thanks!

**Review by sruti1312 — APPROVED** [review]

**Comment by sruti1312** [comment]
Known flaky test causing build failure.

**Comment by dblock** [comment]
> Known flaky test causing build failure.

Consider adding a gradle retry.

**Review by dblock — APPROVED** [review]

**Pull request merged**
