### PR TITLE
Revert 'Remove jackson-databind and jackson-annotations now coming from core (#349)'

### PR DESCRIPTION
**Pull request by ryanbogan**
Signed-off-by: Ryan Bogan <rbogan@amazon.com>

**Is your feature request related to a problem? Please provide an existing Issue # , or describe.**
Jackson is no longer in core, so reverting changes made for https://github.com/opensearch-project/performance-analyzer/issues/344

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dzane17** [comment]
OS core was using jackson v2.14.1. If we are no longer importing from core, we should update to 2.14.1 as well.
ref: https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/version.properties#L11-L12

**Comment by ryanbogan** [comment]
I changed locally and tried to updateSHAs but it's failing with this error:
`Could not find org.opensearch:performanceanalyzer-rca:3.0.0.0-SNAPSHOT.`

Where is that file supposed to be located?

**Comment by kiranprakash154** [comment]
@ryanbogan thanks for the revert PR, let me work on this, i have to try a few things to get this sorted.

**Comment by ryanbogan** [comment]
Addressed in another PR

**Pull request closed without merging**
