### PR TITLE
Staging Version increment automation

### PR DESCRIPTION
**Pull request by prudhvigodithi**
Signed-off-by: pgodithi <pgodithi@amazon.com>

**Is your feature request related to a problem? Please provide an existing Issue # , or describe.**
This is the staging PR for to execute workflows that auto raise the version increment PR's
Example: https://github.com/prudhvigodithi/performance-analyzer/pull/2/files

**Describe the solution you are proposing**
Part of: https://github.com/opensearch-project/opensearch-build/issues/1375
From solution: https://github.com/opensearch-project/opensearch-build/issues/1375#issuecomment-1159476686
Related issue: https://github.com/opensearch-project/performance-analyzer/issues/234

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by sruti1312 — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
Renaming to task updateVersion following https://github.com/opensearch-project/opensearch-plugin-template-java/pull/32.

**Comment by prudhvigodithi** [comment]
Hey @kkhatua @sruti1312 can you please take a look.
Thank you

**Comment by bbarani** [comment]
@kkhatua @sruti1312  can you please review this PR soon?

**Review by sruti1312 — APPROVED** [review]

**Review by kkhatua — APPROVED** [review]

**Review by sgup432 — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
Hey Just checking back to see if we can merge this PR?
Thank you

**Comment by prudhvigodithi** [comment]
Hey @sgup432 @sruti1312 @kkhatua I see the backport failed for 1.3 branch, can you please check ? If required I will raise a manual PR.
Thank you

**Pull request merged**
